### PR TITLE
Andras

### PR DESCRIPTION
**Pull request by andrasschad**
Hey, so this is overly confusing. We have two branches, and I already lost track of this one. I think we should sort this pull request out, then end this branch, and the other one too. Leave only main, and from now on we'll be more careful with branches 😄

### CODE REVIEW

**Review by andrasschad — COMMENTED** [review]
As I see only the README is modified, and the added Diagram.

**Comment by andrasschad** [comment]
Maybe we can delete all the commits, and I can try uploading the modified README and the Diagram only.

**Review by dvadlejch — APPROVED** [review]
Very nice overview! Sorry that it took me so long to have a look. Also, the github cannot show me the pdf file with the diagram. I tried to download it, but I don't know how, so I suggest, we can just merge this file and then I can have a look. Thank you for adding this and let's push the project! :D

**Comment by dvadlejch** [comment]
Exactly as you say, let's just keep a main branch and always merge everything into the main.

**Pull request merged**
